alias tctl="/workspace/bin/tctl"
alias temporal="/workspace/bin/temporal"
alias workspace="cd ${GITPOD_REPO_ROOT}"
alias webui="gp preview $(gp url 8080)"
alias ex1="cd ${GITPOD_REPO_ROOT}/exercises/hello-workflow/practice"
alias ex2="cd ${GITPOD_REPO_ROOT}/exercises/hello-web-ui/practice"
alias ex3="cd ${GITPOD_REPO_ROOT}/exercises/farewell-workflow/practice"
alias ex4="cd ${GITPOD_REPO_ROOT}/exercises/finale-workflow/practice"
alias ex1s="cd ${GITPOD_REPO_ROOT}/exercises/hello-workflow/solution"
alias ex2s="cd ${GITPOD_REPO_ROOT}/exercises/hello-web-ui/solution"
alias ex3s="cd ${GITPOD_REPO_ROOT}/exercises/farewell-workflow/solution"
alias ex4s="cd ${GITPOD_REPO_ROOT}/exercises/finale-workflow/solution"
export PATH="$PATH:/home/gitpod/.temporalio/bin"
echo "temporal configured! try typing temporal -v"
echo "Your workspace is located at: ${GITPOD_REPO_ROOT}"
echo "Type the command     workspace      to return to the workspace directory at any time."
